### ISSUE TITLE
사용자정보 수정요청

### ISSUE THREAD

**Issue by ghost** [seia-soto/Serium#39]
;사용자정보를 치면 

"Sat Jan 20 2018 02:57:18 GMT+0000 (UTC)에 Discord에 가입했습니다."가 나오는데 여기서 "Discord에"를 "Discord를"로 고쳐주세요.

**Comment by seia-soto** [comment]
Fix on next version verbosed

**Comment by seia-soto** [comment]
New request: supporting dynamic presence
