### ISSUE TITLE
전각체 변환기 만들어주세요.

### ISSUE THREAD

**Issue by ghost** [seia-soto/Serium#49]
제목이 곧 내용입니다. 전각체 변환기를 만들어주세요. 근데 이게 가능한지 모르겠네요.

**Comment by RanolP** [comment]
[기술적](https://www.npmjs.com/package/ascii-fullwidth-halfwidth-convert)으로 가능합니다 (!)

**Comment by seia-soto** [comment]
당연히 기술적으로 가능하죠 ㅎㄷㄷ

**Comment by seia-soto** [comment]
그렇게 만드는 중----...
